diagnosis/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'diagnosis'

urlpatterns = [
    path('patient/form/<int:doctor_pk>', PreliminaryDiagnosisFormView.as_view(), name='patient_form'),
    path('patient/diagnosis', PatientDiagnosisView.as_view(), name='patient_diagnosis'),
    path('doctor/list', DoctorListView.as_view(), name='doctor_list'),
    path('doctor/detail/<doctor_pk>', DoctorDetailView.as_view(), name='doctor_detail'),
    path('diagnosis/history/', DiagnosisHistoryView.as_view(), name='diagnosis_history'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('doctor/profile/create/', DoctorProfileCreateView.as_view(), name='doctor_profile_create'),
    path('patient/profile/create/', PatientProfileCreateView.as_view(), name='patient_profile_create'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('doctor-Varifing/', DoctorVarifingView.as_view(), name='octor_varifing'),

    path('role-redirect/', role_redirect, name='role_redirect'),

    path('doctor-dashboard/', DoctorDashboardView.as_view(), name='doctor_dashboard'),
    path('patient-detail/<int:pk>/', AppointmentDetailView.as_view(), name='patient_detail'),
    path('appointment/<int:appointment_id>/change-status/<str:new_status>/', change_appointment_status, name='change_appointment_status'),

    path('chat/<int:receiver_id>/', chat_view, name='chat_view'),
    path('fetch-messages/<int:receiver_id>/', fetch_messages, name='fetch_messages'),

    path('donor/registration/view', donor_registration_view, name='donor_registration'),
    path('donor/registration/confirm', donor_registration_confirm, name='donor_registration_confirm'),
    path('respond-to-request/<int:request_id>/', respond_to_doctor_request, name='respond_to_request'),
    path('doctor/requests/list/', doctor_requests_list, name='doctor_requests_list'),
    
    path('doctor-request/list/', doctor_requests_list_doctor_part, name='doctor_requests_list_doctor_part'),
    path('doctor-request/create/', create_doctor_request, name='create_doctor_request'),
    path('doctor-request/edit/<int:request_id>/', edit_doctor_request, name='edit_doctor_request'),
    path('doctor-request/delete/<int:request_id>/', delete_doctor_request, name='delete_doctor_request'),
     path('discussions/', discussion_list, name='discussion_list'),
    path('discussions/<int:pk>/', discussion_detail, name='discussion_detail'),
    path('discussions/create/', create_discussion, name='create_discussion')
]

mediog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView, LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('diagnosis/', include('diagnosis.urls', namespace='diagnosis'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diagnosis/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    is_patient = models.BooleanField(default=False)
    is_doctor = models.BooleanField(default=False)


class ChatMessage(models.Model):
    sender = models.ForeignKey(User, related_name='sent_messages', on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name='received_messages', on_delete=models.CASCADE)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message from {self.sender} to {self.receiver} at {self.timestamp}"
class Patient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.CharField(max_length=15)
    phone_number = models.CharField(max_length=15)
    identification_number = models.CharField(max_length=15, unique=True, null=True, blank=True)


# Модель для специализаций
class Specialty(models.Model):
    name = models.CharField(max_length=100)  # Название специализации, например, хирург, невролог и т.д.
    description = models.TextField(null=True, blank=True)  # Описание специализации

    def __str__(self):
        return self.name

class City(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    specialties = models.ManyToManyField(Specialty, related_name='doctors')  # Специализации врача
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, related_name='doctors')
    photo = models.FileField(upload_to='licenses/', null=True, blank=True)
    about = models.TextField()
    license = models.FileField(upload_to='licenses/', null=True, blank=True)  # Лицензия на медицинскую практику
    diploma = models.FileField(upload_to='diplomas/', null=True, blank=True)  # Диплом о высшем образовании
    specialization_certificates = models.FileField(upload_to='specializations/', null=True, blank=True)  # Сертификаты специализации
    liability_insurance = models.FileField(upload_to='insurance/', null=True, blank=True)  # Страхование профессиональной ответственности
    identification_document = models.FileField(upload_to='identifications/', null=True, blank=True)  # Идентификационные документы
    phone_number = models.CharField(max_length=15)
    verified = models.BooleanField(default=False)  # Поле для верификации доктора администратором
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return self.user.username

from mediog import settings


class PreliminaryDiagnosis(models.Model):
    # Основная информация
    full_name = models.CharField(max_length=100)
    age = models.IntegerField()
    gender_choices = [
        ('male', 'Мужской'),
        ('female', 'Женский'),
        ('other', 'Другое')
    ]
    gender = models.CharField(max_length=6, choices=gender_choices)

    # Контактная информация
    phone = models.CharField(max_length=20)

    # Текущие Симптомы
    symptoms = models.TextField()
    symptoms_start_choices = [
        ('less_week', 'Менее недели назад'),
        ('one_two_weeks', '1-2 недели назад'),
        ('more_month', 'Более месяца назад')
    ]
    symptoms_start = models.CharField(max_length=15, choices=symptoms_start_choices)
    symptoms_frequency_choices = [
        ('daily', 'Ежедневно'),
        ('several_week', 'Несколько раз в неделю'),
        ('rarely', 'Редко')
    ]
    symptoms_frequency = models.CharField(max_length=15, choices=symptoms_frequency_choices)

    # Медицинская история
    past_diseases_and_surgeries = models.TextField(blank=True)
    chronic_diseases = models.TextField(blank=True)
    family_medical_history = models.TextField(blank=True)

    # Лекарства и добавки
    medications = models.TextField(blank=True)
    supplements = models.TextField(blank=True)

    # Образ жизни
    diet = models.TextField(blank=True)
    physical_activity_level_choices = [
        ('low', 'Низкий'),
        ('moderate', 'Умеренный'),
        ('high', 'Высокий')
    ]
    physical_activity_level = models.CharField(max_length=10, choices=physical_activity_level_choices, blank=True)
    smoking_and_alcohol_choices = [
        ('none', 'Нет'),
        ('smoking', 'Курение'),
        ('alcohol', 'Алкоголь'),
        ('both', 'И то, и другое')
    ]
    smoking_and_alcohol = models.CharField(max_length=10, choices=smoking_and_alcohol_choices, blank=True)

    # Аллергии и реакции
    allergies = models.TextField(blank=True)
    drug_reactions = models.TextField(blank=True)

    # Общее самочувствие
    appetite_and_weight_changes_choices = [
        ('no_change', 'Без изменений'),
        ('increase', 'Увеличение'),
        ('decrease', 'Уменьшение')
    ]
    appetite_and_weight_changes = models.CharField(max_length=10, choices=appetite_and_weight_changes_choices, blank=True)
    sleep_changes_choices = [
        ('normal', 'Нормальный'),
        ('insomnia', 'Бессонница'),
        ('disturbed', 'Нарушенный')
    ]
    sleep_changes = models.CharField(max_length=10, choices=sleep_changes_choices, blank=True)
    stress_and_anxiety_choices = [
        ('none', 'Нет'),
        ('occasional', 'Иногда'),
        ('frequent', 'Часто')
    ]
    stress_and_anxiety = models.CharField(max_length=10, choices=stress_and_anxiety_choices, blank=True)

    def __str__(self):
        return self.full_name

class Appointment(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    date = models.DateTimeField()
    status = models.CharField(max_length=10, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending')

    def __str__(self):
        return f"{self.patient} - {self.doctor} on {self.date.strftime('%Y-%m-%d %H:%M')}"

class DiagnosisHistory(models.Model):
    user = models.ForeignKey(Patient, on_delete=models.CASCADE)
    text = models.TextField()
    patient_text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    appointment = models.OneToOneField(Appointment, on_delete=models.SET_NULL, null=True, blank=True)


class Rating(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    rating = models.IntegerField()
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)


class DonorProfile(models.Model):
    patient = models.OneToOneField(Patient, on_delete=models.CASCADE)
    blood_type = models.CharField(max_length=3)
    age = models.PositiveIntegerField()
    approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Donor profile of {self.patient.user.username}"


class DoctorRequest(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name='doctor_requests')
    title = models.CharField(max_length=255)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Request by {self.doctor.user.username} - {self.title}"


class DonorRequest(models.Model):
    donor_profile = models.ForeignKey(DonorProfile, on_delete=models.CASCADE)
    doctor_request = models.ForeignKey(DoctorRequest, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


from django.db import models
from django.conf import settings

class Discussion(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    photo = models.ImageField(upload_to='discussion_photos/', blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
from django.db import models
from django.conf import settings

class Comment(models.Model):
    discussion = models.ForeignKey(Discussion, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    photo = models.ImageField(upload_to='comment_photos/', blank=True, null=True)  # Поле для фото
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment by {self.user} on {self.discussion}"

templates/doctor_part/donor/create_doctor_request.html
{% extends 'base_doctor.html' %}
{% load static widget_tweaks %}  <!-- Загрузка widget_tweaks -->

{% block content %}
<div class="container" style="position: absolute; top: 150px; left: 50%; transform: translateX(-50%);">
    <h2 class="mb-4" style="margin-left: 320px;">Создать новую заявку на донорство</h2>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post" class="form-floating">
                {% csrf_token %}
                {% for field in form %}
                <div class="mb-3">
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                    {{ field|add_class:'form-control' }}  <!-- Применение класса Bootstrap -->
                    {% if field.help_text %}
                    <div class="form-text">{{ field.help_text }}</div>
                    {% endif %}
                    {% for error in field.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                    {% endfor %}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary mt-3">Создать заявку</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/doctor_part/donor/edit_doctor_request.html
{% extends 'base_doctor.html' %}

{% block content %}
<h2>Редактировать заявку</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить изменения</button>
</form>
{% endblock %}

templates/doctor_part/donor/list.html
{% extends 'base_doctor.html' %}
{% load static %}

{% block content %}
<style>
    .container1 {
        position: absolute;
        margin-top: 120px;
        left: 50%;
        transform: translateX(-50%);
        width: 90%;
    }
    .donor-request-icon {
        display: inline-block;
        float: right;
        background: url('{% static "img/blood-test (1).png" %}') no-repeat center center;
        background-size: cover;
        width: 30px;
        height: 30px;
        margin-right: 10px;
        border: 2px solid #d9534f;
        border-radius: 50%;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
    }
    .btn-custom {
        color: #fff;
        background-color: #d9534f;
        border-color: #d43f3a;
        box-shadow: 0 0 5px rgba(0,0,0,0.5);
        transition: background-color 0.3s ease-in-out, color 0.3s ease-in-out;
    }
    .btn-custom:hover, .btn-custom:focus {
        background-color: #c9302c;
        border-color: #ac2925;
    }
    .btn-info-custom {
        color: #fff;
        background-color: #5bc0de;
        border-color: #46b8da;
        box-shadow: 0 0 5px rgba(0,0,0,0.3);
        transition: background-color 0.3s ease-in-out, color 0.3s ease-in-out;
    }
    .btn-info-custom:hover, .btn-info-custom:focus {
        background-color: #31b0d5;
        border-color: #269abc;
    }
</style>

<div class="container1">
    <a href="{% url 'diagnosis:create_doctor_request' %}" class="btn btn-custom mb-3">Создать заявку на донорство</a>
    
    <!-- Tabs -->
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id="all-requests-tab" data-bs-toggle="tab" data-bs-target="#all-requests" type="button" role="tab" aria-controls="all-requests" aria-selected="true">Все заявки на донорство</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="my-requests-tab" data-bs-toggle="tab" data-bs-target="#my-requests" type="button" role="tab" aria-controls="my-requests" aria-selected="false">Мои заявки</button>
        </li>
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="all-requests" role="tabpanel" aria-labelledby="all-requests-tab">
            <ul class="list-unstyled">
                {% for request in all_requests %}
                <li class="mb-3 p-3 shadow rounded">
                    <span class="donor-request-icon"></span>
                    <h3>{{ request.title }}</h3>
                    <p>{{ request.description }}</p>
                    <p>Количество откликов: {{ request.response_count }}</p>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="tab-pane fade" id="my-requests" role="tabpanel" aria-labelledby="my-requests-tab">
            <ul class="list-unstyled">
                {% if doctor_own_requests %}
                {% for request in doctor_own_requests %}
                <li class="mb-3 p-3 shadow rounded">
                    <span class="donor-request-icon"></span>
                    <h3>{{ request.title }}</h3>
                    <p>{{ request.description }}</p>
                    <a href="{% url 'diagnosis:delete_doctor_request' request.id %}" class="btn btn-danger" onclick="return confirm('Вы уверены?');">Удалить</a>
                    <h4>Отклики:</h4>
                    <ul class="list-unstyled ps-3">
                        {% for response in request.donorrequest_set.all %}
                        <li>{{ response.donor_profile.patient.user.get_full_name }} - {{ response.created_at }}<br>
                        {{ response.donor_profile.patient.email }} - {{ response.donor_profile.patient.phone_number }}</li>
                        {% empty %}
                        <li>На эту заявку пока нет откликов.</li>
                        {% endfor %}
                    </ul>
                </li>
                {% endfor %}
                {% endif %}
            </ul>
        </div>
    </div>
</div>

<script>
    // Bootstrap's JavaScript needs Popper.js and Bootstrap JS
    // They should be included in your base template if they are not yet included
    // Example of including them:
    // <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2/dist/umd/popper.min.js"></script>
    // <script src="https://cdn.jsdelivr.net/npm/bootstrap@5/dist/js/bootstrap.min.js"></script>
</script>
{% endblock %}