diagnosis/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'diagnosis'

urlpatterns = [
    path('patient/form/<int:doctor_pk>', PreliminaryDiagnosisFormView.as_view(), name='patient_form'),
    path('patient/diagnosis', PatientDiagnosisView.as_view(), name='patient_diagnosis'),
    path('doctor/list', DoctorListView.as_view(), name='doctor_list'),
    path('doctor/detail/<doctor_pk>', DoctorDetailView.as_view(), name='doctor_detail'),
    path('diagnosis/history/', DiagnosisHistoryView.as_view(), name='diagnosis_history'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('doctor/profile/create/', DoctorProfileCreateView.as_view(), name='doctor_profile_create'),
    path('patient/profile/create/', PatientProfileCreateView.as_view(), name='patient_profile_create'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('doctor-Varifing/', DoctorVarifingView.as_view(), name='octor_varifing'),

    path('role-redirect/', role_redirect, name='role_redirect'),

    path('doctor-dashboard/', DoctorDashboardView.as_view(), name='doctor_dashboard'),
    path('patient-detail/<int:pk>/', AppointmentDetailView.as_view(), name='patient_detail'),
    path('appointment/<int:appointment_id>/change-status/<str:new_status>/', change_appointment_status, name='change_appointment_status'),

    path('chat/<int:receiver_id>/', chat_view, name='chat_view'),
    path('fetch-messages/<int:receiver_id>/', fetch_messages, name='fetch_messages'),

    path('donor/registration/view', donor_registration_view, name='donor_registration'),
    path('donor/registration/confirm', donor_registration_confirm, name='donor_registration_confirm'),
    path('respond-to-request/<int:request_id>/', respond_to_doctor_request, name='respond_to_request'),
    path('doctor/requests/list/', doctor_requests_list, name='doctor_requests_list'),
    
    path('doctor-request/list/', doctor_requests_list_doctor_part, name='doctor_requests_list_doctor_part'),
    path('doctor-request/create/', create_doctor_request, name='create_doctor_request'),
    path('doctor-request/edit/<int:request_id>/', edit_doctor_request, name='edit_doctor_request'),
    path('doctor-request/delete/<int:request_id>/', delete_doctor_request, name='delete_doctor_request'),
     path('discussions/', discussion_list, name='discussion_list'),
    path('discussions/<int:pk>/', discussion_detail, name='discussion_detail'),
    path('discussions/create/', create_discussion, name='create_discussion')
]

mediog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView, LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('diagnosis/', include('diagnosis.urls', namespace='diagnosis'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/doctors/detail.html
{% extends 'base.html' %}
{% load static %}
{% load diagnosis_tags %}
{% block content %}
<div class="breadcrumb-bar">
</div>
<div class="content">
			<div class="container">

				<div class="card">
            <div class="card-body">
                <div class="doctor-widget">
                    <div class="doc-info-left">
                        <div class="doctor-img">
                            <a href="{% url 'diagnosis:doctor_detail' doctor.id %}">
                                <img src="{{doctor.photo.url}}" class="img-fluid" alt="User Image">
                            </a>
                        </div>
                        <div class="doc-info-cont">
                            <h4 class="doc-name"><a href="{% url 'diagnosis:doctor_detail' doctor.id %}">{{doctor.user.get_full_name}}</a></h4>
                            <p class="doc-speciality">
                                {% for specialty in doctor.specialties.all %}
                                    {{ specialty.name }}
                                {% endfor %}
                            </p>
                            <p>{{doctor.phone_number}}</p>
                            <div class="rating">
                                {% render_stars doctor.pk %}
                                <span class="d-inline-block average-rating">({% get_doctor_reviews_count doctor_pk=doctor.pk %})</span>
                            </div>
                            <div class="clinic-details">
                                <p class="doc-location"><i class="fas fa-map-marker-alt"></i> {{doctor.city.name}}</p>
                            </div>
                        </div>
                    </div>
                    <div class="doc-info-right">
                        <div class="clini-infos">
                            <ul>
                                <li><i class="far fa-thumbs-up"></i> {% get_doctor_rating doctor_pk=doctor.pk %}</li>
                                <li><i class="far fa-comment"></i> {% get_doctor_reviews_count doctor_pk=doctor.pk %}</li>
                                <li><i class="fas fa-map-marker-alt"></i> {{doctor.city.name}}</li>
                                <li><i class="far fa-money-bill-alt"></i> {{doctor.price}} тг </li>
                            </ul>
                        </div>
						<div class="doctor-action">
									<a href="mailto:{{doctor.user.email}}" class="btn btn-white fav-btn">
										<i class="fas fa-envelope"></i>
									</a>
									<a href="tel:{{doctor.phone_number}}" class="btn btn-white call-btn">
										<i class="fas fa-phone"></i>
									</a>
									<a href="{% url 'diagnosis:chat_view' doctor.user.id %}" class="btn btn-white msg-btn">
										<i class="far fa-comment-alt"></i>
									</a>

								</div>
                        <div class="clinic-booking">
                            <a class="apt-btn" href="{% url 'diagnosis:chat_view' doctor.user.id %}">Чат</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>


				<div class="card">
					<div class="card-body pt-0">

						<nav class="user-tabs mb-4">
							<ul class="nav nav-tabs nav-tabs-bottom nav-justified" role="tablist">
								<li class="nav-item" role="presentation">
									<a class="nav-link" href="#doc_overview" data-bs-toggle="tab" aria-selected="false" role="tab" tabindex="-1">Обзор</a>
								</li>
								<li class="nav-item" role="presentation">
									<a class="nav-link" href="#doc_locations" data-bs-toggle="tab" aria-selected="false" role="tab" tabindex="-1">Записи</a>
								</li>
								<li class="nav-item" role="presentation">
									<a class="nav-link active" href="#doc_reviews" data-bs-toggle="tab" aria-selected="true" role="tab">Отзыв</a>
								</li>

							</ul>
						</nav>


						<div class="tab-content pt-0">

							<div role="tabpanel" id="doc_overview" class="tab-pane fade">
								<div class="row">
									<div class="col-md-12 col-lg-9">

										<div class="widget about-widget">
											<h4 class="widget-title">Доктор.</h4>
											<p>{{doctor.about}}</p>
										</div>
									</div>
								</div>
							</div>


							<div role="tabpanel" id="doc_locations" class="tab-pane fade">
  <div class="location-list">
    <div class="row">
      <div class="card booking-schedule schedule-widget">

        <!-- Dynamic Dates Navigation (if needed) -->
        <div class="schedule-header">
          <div class="row">
            <div class="col-md-12">
              <div class="day-slot">
                <ul>
                  <!-- Insert dynamic left arrow functionality if applicable -->
                  <li class="left-arrow">
                    <a href="javascript:void(0)">
                      <i class="fa fa-chevron-left"></i>
                    </a>
                  </li>
                  <!-- Dynamic Dates Here -->
                  {% for date, slots in slots.items %}
                  <li>
                    <span>{{ date | date:"D" }}</span>
                    <span class="slot-date">{{ date | date:"d M" }} <small class="slot-year">{{ date | date:"Y" }}</small></span>
                  </li>
                  {% endfor %}
                  <!-- Insert dynamic right arrow functionality if applicable -->
                  <li class="right-arrow">
                    <a href="javascript:void(0)">
                      <i class="fa fa-chevron-right"></i>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- Time Slots -->
        <div class="schedule-cont">
          <div class="row">
            <div class="col-md-12">
              <div class="time-slot">
                <ul class="clearfix">
                  {% for date, slots in slots.items %}
                  <li>
                    {% for slot in slots %}
                    <a class="timing" href="{% url 'diagnosis:patient_form' doctor.id %}?date={{ date }}&slot={{ slot }}">
                      <span>{{ slot }}</span>
                    </a>
                    {% endfor %}
                  </li>
                  {% empty %}
                  <li>Нет доступных временных слотов.</li>
                  {% endfor %}
                </ul>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>



							<div role="tabpanel" id="doc_reviews" class="tab-pane fade active show">

								<div class="widget review-listing">
									<ul class="comments-list">
									{% for rating in ratings %}
										<li>
											<div class="comment">
												<img class="avatar avatar-sm rounded-circle" alt="User Image" src="{% static 'img/patient_logo.png' %}">
												<div class="comment-body">
													<div class="meta-data">
														<span class="comment-author">{{rating.patient.user.username}}</span>
														<span class="comment-date">{{rating.date}}</span>
														<div class="review-count rating">
															{% render_stars_for_detail_page rating.rating %}
														</div>
													</div>
													<p class="comment-content">
														{{rating.text}}
													</p>
													<div class="comment-reply">


													</div>
												</div>
											</div>
										</li>
									{% endfor %}




									</ul>

									<div class="all-feedback text-center">

									</div>

								</div>


								<div class="write-review">
									<h4>Написать отзыв о  <strong>Докторе {{doctor.user.get_full_name}}</strong></h4>

									<form action="{% url 'diagnosis:doctor_detail' doctor.id %}" method="post">
										{% csrf_token %}
										<div class="mb-3">
											<label class="mb-2">Шкала</label>
											<div class="star-rating">
												<input id="star-5" type="radio" name="rating" value="5">
												<label for="star-5" title="5 stars">
													<i class="active fa fa-star"></i>
												</label>
												<input id="star-4" type="radio" name="rating" value="4">
												<label for="star-4" title="4 stars">
													<i class="active fa fa-star"></i>
												</label>
												<input id="star-3" type="radio" name="rating" value="3">
												<label for="star-3" title="3 stars">
													<i class="active fa fa-star"></i>
												</label>
												<input id="star-2" type="radio" name="rating" value="2">
												<label for="star-2" title="2 stars">
													<i class="active fa fa-star"></i>
												</label>
												<input id="star-1" type="radio" name="rating" value="1">
												<label for="star-1" title="1 star">
													<i class="active fa fa-star"></i>
												</label>
											</div>
										</div>
										<div class="mb-3">
											<label class="mb-2">Ваш отзыв</label>
											<textarea id="review_desc" maxlength="100" name="text" class="form-control"></textarea>
											<div class="d-flex justify-content-between mt-3"><small class="text-muted"Осталось ><span id="chars">100</span> символов</small></div>
										</div>
										<hr>
										<div class="mb-3">
											<div class="terms-accept">
												<div class="custom-checkbox">
													<input type="checkbox" id="terms_accept">
													<label for="terms_accept">Я прочитал и принимаю Условия использования</label>
												</div>
											</div>
										</div>
										<div class="submit-section">
											<button type="submit" class="btn btn-primary submit-btn">Добавить отзыв</button>
										</div>
									</form>

								</div>

							</div>




						</div>
					</div>
				</div>

			</div>
		</div>
{% endblock %}

templates/doctors/list.html
{% extends 'base.html' %}
{% load static %}
{% load diagnosis_tags %}
{% block content %}
<div class="breadcrumb-bar">
</div>


			<div class="content" style="transform: none; min-height: 107.24px;">
				<div class="container" style="transform: none;">
					<div class="row" style="transform: none;">
						<div class="col-md-12 col-lg-4 col-xl-3 theiaStickySidebar" style="position: relative; overflow: visible; box-sizing: border-box; min-height: 1px;">



							<div class="theiaStickySidebar" style="padding-top: 0px; padding-bottom: 1px; position: static; transform: none; top: 0px; left: 73.6667px;"><div class="card search-filter">
								<div class="card-header">
									<h4 class="card-title mb-0">Поиск</h4>
								</div>
								<div class="card-body">
									<form action="{% url 'diagnosis:doctor_list' %}" method="get">
									<div class="filter-widget">
										<div >
											<input type="search" class="form-control" {% if search_text %} value="{{search_text}}" {% endif %} name="search_text" placeholder="Поиск по врачу">
										</div>
									</div>
									<!-- <div class="filter-widget">-->
<!--										<h4>Пол</h4>-->
<!--										<div>-->
<!--											<label class="custom_check">-->
<!--												<input type="checkbox" name="gender_type" checked="">-->
<!--												<span class="checkmark"></span> Доктор-мужчина-->
<!--											</label>-->
<!--										</div>-->
<!--										<div>-->
<!--											<label class="custom_check">-->
<!--												<input type="checkbox" name="gender_type">-->
<!--												<span class="checkmark"></span> Доктор-женщина-->
<!--											</label>-->
<!--										</div>-->
<!--									</div>-->
<!--									<div class="filter-widget">-->
<!--										<h4>Select Specialist</h4>-->
<!--										<div>-->
<!--											<label class="custom_check">-->
<!--												<input type="checkbox" name="select_specialist" checked="">-->
<!--												<span class="checkmark"></span> Urology-->
<!--											</label>-->
<!--										</div>-->
<!--										<div>-->
<!--											<label class="custom_check">-->
<!--												<input type="checkbox" name="select_specialist" checked="">-->
<!--												<span class="checkmark"></span> Neurology-->
<!--											</label>
<!--										</div>-
<!--									</div> -->
									<div class="btn-search">
										<button type="submit" class="btn w-100">искать</button>
									</div>
									</form>
								</div>
							</div><div class="resize-sensor" style="position: absolute; inset: 0px; overflow: hidden; z-index: -1; visibility: hidden;"><div class="resize-sensor-expand" style="position: absolute; left: 0; top: 0; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden;"><div style="position: absolute; left: 0px; top: 0px; transition: all 0s ease 0s; width: 295px; height: 1702px;"></div></div><div class="resize-sensor-shrink" style="position: absolute; left: 0; top: 0; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden;"><div style="position: absolute; left: 0; top: 0; transition: 0s; width: 200%; height: 200%"></div></div></div></div></div>
							<div class="col-md-12 col-lg-8 col-xl-9">
							{% for doctor in doctors %}
								<div class="card">
									<div class="card-body">
										<div class="doctor-widget">
											<div class="doc-info-left">
												<div class="doctor-img">
													<a href="{% url 'diagnosis:doctor_detail' doctor.id %}">
														<img src="{{doctor.photo.url}}" class="img-fluid" alt="User Image">
													</a>
												</div>
												<div class="doc-info-cont">
													<h4 class="doc-name"><a href="{% url 'diagnosis:doctor_detail' doctor.id %}">Dr. {{doctor.user.get_full_name}}</a></h4>
													<p class="doc-speciality">
														{{doctor.about}}
													</p>
													<h5 class="doc-department">
														{% for specialty in doctor.specialties.all %}
                                            				{{ specialty.name }}
                                       					{% endfor %}
													</h5>
													<div class="rating">
														{% render_stars doctor.pk %}
                                        				<span class="d-inline-block average-rating">({% get_doctor_reviews_count doctor_pk=doctor.pk %})</span>
													</div>
													<div class="clinic-details">
														<p class="doc-location"><i class="fas fa-map-marker-alt"></i>{{doctor.city.name}}</p>
													</div>
												</div>
											</div>
											<div class="doc-info-right">
												<div class="clini-infos">
													<ul>
														<li><i class="far fa-thumbs-up"></i> {% get_doctor_rating doctor_pk=doctor.pk %}</li>
														<li><i class="far fa-comment"></i> {% get_doctor_reviews_count doctor_pk=doctor.pk %}</li>
														<li><i class="fas fa-map-marker-alt"></i> {{doctor.city.name}}</li>
														<li><i class="far fa-money-bill-alt"></i> {{doctor.price}} <i class="fas fa-info-circle" data-bs-toggle="tooltip" aria-label="Lorem Ipsum" data-bs-original-title="Lorem Ipsum"></i></li>
													</ul>
												</div>
												<div class="clinic-booking">
													<a class="view-pro-btn" href="{% url 'diagnosis:doctor_detail' doctor.id %}">Просмотреть профиль</a>
													<a class="apt-btn" href="{% url 'diagnosis:doctor_detail' doctor.id %}">Записаться на прием</a>
												</div>
											</div>
										</div>
									</div>
								</div>
								{% endfor %}

								<div class="row">
									<div class="col-sm-12">
										<div class="blog-pagination rev-page">
											<nav>
												<ul class="pagination justify-content-center">
													<li class="page-item disabled">
														<a class="page-link page-prev" href="#" tabindex="-1"><i class="feather-chevrons-left me-1"></i> ПРЕД.</a>
													</li>
													<li class="page-item active">
														<a class="page-link" href="#">1</a>
													</li>
													<li class="page-item">
														<a class="page-link" href="#">2</a>
													</li>
													<li class="page-item">
														<a class="page-link" href="#">...</a>
													</li>
													<li class="page-item">
														<a class="page-link" href="#">10</a>
													</li>
													<li class="page-item">
														<a class="page-link page-next" href="#">СЛЕД. <i class="feather-chevrons-right ms-1"></i></a>
													</li>
												</ul>
											</nav>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

{% endblock %}

templates/doctors/waiting_varify.html
{% extends 'base.html' %}
{% load static %}
{% load diagnosis_tags %}
{% block content %}
<div class="breadcrumb-bar">

			</div>
<div class="content" style="transform: none; min-height: 107.24px;">
				<div class="container" style="transform: none;">
					<div class="row justify-content-center">
						<div class="col-lg-6">

							<div class="card success-card">
								<div class="card-body">
									<div class="success-cont">
										<i class="fas fa-check"></i>
										<h3>Ваша заявка на регистрацию в качестве доктора находится на рассмотрении</h3>
										<p>Каждая заявка тщательно проверяется нашими модераторами, чтобы обеспечить безопасность и качество сервиса для всех пользователей.</p>
									</div>
								</div>
							</div>

						</div>
					</div>

					</div>
				</div>
{% endblock %}