diagnosis/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'diagnosis'

urlpatterns = [
    path('patient/form/<int:doctor_pk>', PreliminaryDiagnosisFormView.as_view(), name='patient_form'),
    path('patient/diagnosis', PatientDiagnosisView.as_view(), name='patient_diagnosis'),
    path('doctor/list', DoctorListView.as_view(), name='doctor_list'),
    path('doctor/detail/<doctor_pk>', DoctorDetailView.as_view(), name='doctor_detail'),
    path('diagnosis/history/', DiagnosisHistoryView.as_view(), name='diagnosis_history'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('doctor/profile/create/', DoctorProfileCreateView.as_view(), name='doctor_profile_create'),
    path('patient/profile/create/', PatientProfileCreateView.as_view(), name='patient_profile_create'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('doctor-Varifing/', DoctorVarifingView.as_view(), name='octor_varifing'),

    path('role-redirect/', role_redirect, name='role_redirect'),

    path('doctor-dashboard/', DoctorDashboardView.as_view(), name='doctor_dashboard'),
    path('patient-detail/<int:pk>/', AppointmentDetailView.as_view(), name='patient_detail'),
    path('appointment/<int:appointment_id>/change-status/<str:new_status>/', change_appointment_status, name='change_appointment_status'),

    path('chat/<int:receiver_id>/', chat_view, name='chat_view'),
    path('fetch-messages/<int:receiver_id>/', fetch_messages, name='fetch_messages'),

    path('donor/registration/view', donor_registration_view, name='donor_registration'),
    path('donor/registration/confirm', donor_registration_confirm, name='donor_registration_confirm'),
    path('respond-to-request/<int:request_id>/', respond_to_doctor_request, name='respond_to_request'),
    path('doctor/requests/list/', doctor_requests_list, name='doctor_requests_list'),
    
    path('doctor-request/list/', doctor_requests_list_doctor_part, name='doctor_requests_list_doctor_part'),
    path('doctor-request/create/', create_doctor_request, name='create_doctor_request'),
    path('doctor-request/edit/<int:request_id>/', edit_doctor_request, name='edit_doctor_request'),
    path('doctor-request/delete/<int:request_id>/', delete_doctor_request, name='delete_doctor_request'),
     path('discussions/', discussion_list, name='discussion_list'),
    path('discussions/<int:pk>/', discussion_detail, name='discussion_detail'),
    path('discussions/create/', create_discussion, name='create_discussion')
]

mediog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView, LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('diagnosis/', include('diagnosis.urls', namespace='diagnosis'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diagnosis/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    is_patient = models.BooleanField(default=False)
    is_doctor = models.BooleanField(default=False)


class ChatMessage(models.Model):
    sender = models.ForeignKey(User, related_name='sent_messages', on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name='received_messages', on_delete=models.CASCADE)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message from {self.sender} to {self.receiver} at {self.timestamp}"
class Patient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.CharField(max_length=15)
    phone_number = models.CharField(max_length=15)
    identification_number = models.CharField(max_length=15, unique=True, null=True, blank=True)


# Модель для специализаций
class Specialty(models.Model):
    name = models.CharField(max_length=100)  # Название специализации, например, хирург, невролог и т.д.
    description = models.TextField(null=True, blank=True)  # Описание специализации

    def __str__(self):
        return self.name

class City(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    specialties = models.ManyToManyField(Specialty, related_name='doctors')  # Специализации врача
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, related_name='doctors')
    photo = models.FileField(upload_to='licenses/', null=True, blank=True)
    about = models.TextField()
    license = models.FileField(upload_to='licenses/', null=True, blank=True)  # Лицензия на медицинскую практику
    diploma = models.FileField(upload_to='diplomas/', null=True, blank=True)  # Диплом о высшем образовании
    specialization_certificates = models.FileField(upload_to='specializations/', null=True, blank=True)  # Сертификаты специализации
    liability_insurance = models.FileField(upload_to='insurance/', null=True, blank=True)  # Страхование профессиональной ответственности
    identification_document = models.FileField(upload_to='identifications/', null=True, blank=True)  # Идентификационные документы
    phone_number = models.CharField(max_length=15)
    verified = models.BooleanField(default=False)  # Поле для верификации доктора администратором
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return self.user.username

from mediog import settings


class PreliminaryDiagnosis(models.Model):
    # Основная информация
    full_name = models.CharField(max_length=100)
    age = models.IntegerField()
    gender_choices = [
        ('male', 'Мужской'),
        ('female', 'Женский'),
        ('other', 'Другое')
    ]
    gender = models.CharField(max_length=6, choices=gender_choices)

    # Контактная информация
    phone = models.CharField(max_length=20)

    # Текущие Симптомы
    symptoms = models.TextField()
    symptoms_start_choices = [
        ('less_week', 'Менее недели назад'),
        ('one_two_weeks', '1-2 недели назад'),
        ('more_month', 'Более месяца назад')
    ]
    symptoms_start = models.CharField(max_length=15, choices=symptoms_start_choices)
    symptoms_frequency_choices = [
        ('daily', 'Ежедневно'),
        ('several_week', 'Несколько раз в неделю'),
        ('rarely', 'Редко')
    ]
    symptoms_frequency = models.CharField(max_length=15, choices=symptoms_frequency_choices)

    # Медицинская история
    past_diseases_and_surgeries = models.TextField(blank=True)
    chronic_diseases = models.TextField(blank=True)
    family_medical_history = models.TextField(blank=True)

    # Лекарства и добавки
    medications = models.TextField(blank=True)
    supplements = models.TextField(blank=True)

    # Образ жизни
    diet = models.TextField(blank=True)
    physical_activity_level_choices = [
        ('low', 'Низкий'),
        ('moderate', 'Умеренный'),
        ('high', 'Высокий')
    ]
    physical_activity_level = models.CharField(max_length=10, choices=physical_activity_level_choices, blank=True)
    smoking_and_alcohol_choices = [
        ('none', 'Нет'),
        ('smoking', 'Курение'),
        ('alcohol', 'Алкоголь'),
        ('both', 'И то, и другое')
    ]
    smoking_and_alcohol = models.CharField(max_length=10, choices=smoking_and_alcohol_choices, blank=True)

    # Аллергии и реакции
    allergies = models.TextField(blank=True)
    drug_reactions = models.TextField(blank=True)

    # Общее самочувствие
    appetite_and_weight_changes_choices = [
        ('no_change', 'Без изменений'),
        ('increase', 'Увеличение'),
        ('decrease', 'Уменьшение')
    ]
    appetite_and_weight_changes = models.CharField(max_length=10, choices=appetite_and_weight_changes_choices, blank=True)
    sleep_changes_choices = [
        ('normal', 'Нормальный'),
        ('insomnia', 'Бессонница'),
        ('disturbed', 'Нарушенный')
    ]
    sleep_changes = models.CharField(max_length=10, choices=sleep_changes_choices, blank=True)
    stress_and_anxiety_choices = [
        ('none', 'Нет'),
        ('occasional', 'Иногда'),
        ('frequent', 'Часто')
    ]
    stress_and_anxiety = models.CharField(max_length=10, choices=stress_and_anxiety_choices, blank=True)

    def __str__(self):
        return self.full_name

class Appointment(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    date = models.DateTimeField()
    status = models.CharField(max_length=10, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending')

    def __str__(self):
        return f"{self.patient} - {self.doctor} on {self.date.strftime('%Y-%m-%d %H:%M')}"

class DiagnosisHistory(models.Model):
    user = models.ForeignKey(Patient, on_delete=models.CASCADE)
    text = models.TextField()
    patient_text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    appointment = models.OneToOneField(Appointment, on_delete=models.SET_NULL, null=True, blank=True)


class Rating(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    rating = models.IntegerField()
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)


class DonorProfile(models.Model):
    patient = models.OneToOneField(Patient, on_delete=models.CASCADE)
    blood_type = models.CharField(max_length=3)
    age = models.PositiveIntegerField()
    approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Donor profile of {self.patient.user.username}"


class DoctorRequest(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name='doctor_requests')
    title = models.CharField(max_length=255)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Request by {self.doctor.user.username} - {self.title}"


class DonorRequest(models.Model):
    donor_profile = models.ForeignKey(DonorProfile, on_delete=models.CASCADE)
    doctor_request = models.ForeignKey(DoctorRequest, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


from django.db import models
from django.conf import settings

class Discussion(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    photo = models.ImageField(upload_to='discussion_photos/', blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
from django.db import models
from django.conf import settings

class Comment(models.Model):
    discussion = models.ForeignKey(Discussion, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    photo = models.ImageField(upload_to='comment_photos/', blank=True, null=True)  # Поле для фото
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment by {self.user} on {self.discussion}"

templates/doctor_part/doctor_dashboard.html
{% extends 'base_doctor.html' %}
{% load widget_tweaks %}
{% load static %}
{% block content %}



<div class="breadcrumb-bar">
			</div>

			<div class="content" style="transform: none; min-height: 107.24px;">
				<div class="container" style="transform: none;">
					<div class="row" style="transform: none;">
						<div class="col-md-5 col-lg-4 col-xl-3 theiaStickySidebar" style="position: relative; overflow: visible; box-sizing: border-box; min-height: 1px;">



							<div class="theiaStickySidebar" style="padding-top: 0px; padding-bottom: 1px; position: static; transform: none; top: 0px; left: 73.6667px;"><div class="profile-sidebar">
								<div class="widget-profile pro-widget-content">
									<div class="profile-info-widget">
										<a href="#" class="booking-doc-img">
											<img src="{% static 'img/patient_logo.png' %}" alt="User Image">
										</a>
										<div class="profile-det-info">
											<h3>Dr. {{request.user.get_full_name}}</h3>
											<div class="patient-details">
												<h5 class="mb-0">Доктор</h5>
											</div>
										</div>
									</div>
								</div>
								<div class="dashboard-widget">
									<nav class="dashboard-menu">
										<ul>
											<li class="active">
												<a href="">
													<i class="fas fa-columns"></i>
													<span>Пациенты</span>
												</a>
											</li>
											<li>
												<a href="{% url 'diagnosis:doctor_requests_list_doctor_part' %}">
													<i class="fas fa-columns"></i>
													<span>Пациенты</span>
												</a>
											</li>
											<li>
												<a href="{% url 'login' %}">
													<i class="fas fa-sign-out-alt"></i>
													<span>Выйти</span>
												</a>
											</li>
										</ul>
									</nav>
								</div>
							</div><div class="resize-sensor" style="position: absolute; inset: 0px; overflow: hidden; z-index: -1; visibility: hidden;"><div class="resize-sensor-expand" style="position: absolute; left: 0; top: 0; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden;"><div style="position: absolute; left: 0px; top: 0px; transition: all 0s ease 0s; width: 295px; height: 500px;"></div></div><div class="resize-sensor-shrink" style="position: absolute; left: 0; top: 0; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden;"><div style="position: absolute; left: 0; top: 0; transition: 0s; width: 200%; height: 200%"></div></div></div></div></div>
							<div class="col-md-7 col-lg-8 col-xl-9">
								<div class="row">
									<div class="col-md-12">
										<div class="card dash-card">
											<div class="card-body">
												<div class="row">
													<div class="col-md-12 col-lg-4">
														<div class="dash-widget dct-border-rht">
															<div class="circle-bar circle-bar1">
																<div class="circle-graph1" data-percent="75"><canvas width="600" height="600" style="height: 400px; width: 400px;"></canvas>
																	<img src="{% static 'img/patient_logo.png' %}" class="img-fluid" alt="patient">
																</div>
															</div>
															<div class="dash-widget-info">
																<h6>Всего пациентов</h6>
																<h3>{{ total_patients_count }}</h3>
																<p class="text-muted">За все время</p>
															</div>
														</div>
													</div>
													<div class="col-md-12 col-lg-4">
														<div class="dash-widget dct-border-rht">
															<div class="circle-bar circle-bar2">
																<div class="circle-graph2" data-percent="65"><canvas width="600" height="600" style="height: 400px; width: 400px;"></canvas>
																	<img src="{% static 'img/patient_logo.png' %}" class="img-fluid" alt="Patient">
																</div>
															</div>
															<div class="dash-widget-info">
																<h6>Всего пациентов</h6>
																<h3>{{ today_patients_count }}</h3>
																<p class="text-muted">Сегодня</p>
															</div>
														</div>
													</div>
													<div class="col-md-12 col-lg-4">
														<div class="dash-widget">
															<div class="circle-bar circle-bar3">
																<div class="circle-graph3" data-percent="50"><canvas width="600" height="600" style="height: 400px; width: 400px;"></canvas>
																	<img src="{% static 'img/patient_logo.png' %}" class="img-fluid" alt="Patient">
																</div>
															</div>
															<div class="dash-widget-info">
																<h6>Записи</h6>
																<h3>{{ today_appointments_count }}</h3>
																<p class="text-muted">Сегодня</p>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-md-12">
										<h4 class="mb-4">Записи</h4>
										<div class="appointment-tab">

                                            <form method="get">
											<ul class="nav nav-tabs nav-tabs-solid nav-tabs-rounded" role="tablist">

												<li class="nav-item" role="presentation" style="padding:3px;">
                                                    {{ search_form.identification_number|add_class:"form-control"}}
												</li>
                                                <li class="nav-item" role="presentation" style="padding:3px;">
                                                    {{ search_form.period|add_class:"form-control"}}
												</li>
												<li class="nav-item" role="presentation" style="padding:3px;">
                                                    <button class="btn btn-success" type="submit" name="period" value="today">На сегодня</button>
												</li>
                                                <li class="nav-item" role="presentation" style="padding:3px;">
                                                    <button class="btn btn-success" type="submit" name="period" value="next_week">На следующую неделю</button>
												</li>
                                                <li class="nav-item" role="presentation" style="padding:3px;">
                                                    <button class="btn btn-success" type="submit" name="period" value="next_month">На следующий месяц</button>
												</li>

											</ul>
                                            </form>

											<div class="">
												<div class="tab-pane" >
													<div class="card card-table mb-0">
														<div class="card-body">
															<div class="table-responsive">
																<table class="table table-hover table-center mb-0">
																	<thead>
																		<tr>
																			<th>ФИО</th>
																			<th>ИИН</th>
																			<th>Дата</th>
																			<th>Действие</th>
																		</tr>
																	</thead>
																	<tbody>

                                                                       {% if appointments %}
                                                                        {% for appointment in appointments %}
																		<tr>
																			<td>
																				<h2 class="table-avatar">
																					<a href="{% url 'diagnosis:patient_detail' appointment.id %}">{{ appointment.patient.user.get_full_name }} <span>#{{ appointment.id }}</span></a>
																				</h2>
																			</td>
                                                                            <td>{{ appointment.patient.identification_number }}</td>
																			<td>{{ appointment.date }}</td>
																			<td>
																				<div class="table-action">
																					<a href="{% url 'diagnosis:patient_detail' appointment.id %}" class="btn btn-sm bg-info-light">
																						<i class="far fa-eye"></i> посмотреть
																					</a>
																				</div>
																			</td>
																		</tr>
                                                                    {% endfor %}
{% endif %}
																	</tbody>
																</table>
															</div>
														</div>
													</div>
												</div>

											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

{% endblock %}

templates/doctor_part/patient_detail.html
{% extends 'base_doctor.html' %}
{% load static %}
{% block content %}

<div class="breadcrumb-bar">

			</div>


			<div class="content" style="transform: none; min-height: 107.24px;">
				<div class="container" style="transform: none;">
					<div class="row" style="transform: none;">
						<div class="col-md-5 col-lg-4 col-xl-3 theiaStickySidebar dct-dashbd-lft" style="position: relative; overflow: visible; box-sizing: border-box; min-height: 1px;">

							<div class="theiaStickySidebar" style="padding-top: 0px; padding-bottom: 1px; position: static; transform: none; top: 0px; left: 73.6667px;"><div class="card widget-profile pat-widget-profile">
								<div class="card-body">
									<div class="pro-widget-content">
										<div class="profile-info-widget">
											<a href="#" class="booking-doc-img">
												<img src="{% static 'img/patient_logo.png' %}" alt="User Image">
											</a>
											<div class="profile-det-info">
												<h3>{{ appointment.patient.user.get_full_name }}</h3>
												<div class="patient-details">
													<h5><b>ИИН пациента :</b> {{ appointment.patient.identification_number }}</h5>
												</div>
											</div>
										</div>
									</div>
									<div class="patient-info">
										<ul>
											<li>Телефон <span>{{ appointment.patient.phone_number }}</span></li>
											<li>Email <span>{{ appointment.patient.email }}</span></li>
										</ul>
									</div>
								</div>
							</div>
                                <div class="resize-sensor" style="position: absolute; inset: 0px; overflow: hidden; z-index: -1; visibility: hidden;"><div class="resize-sensor-expand" style="position: absolute; left: 0; top: 0; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden;"><div style="position: absolute; left: 0px; top: 0px; transition: all 0s ease 0s; width: 295px; height: 642px;"></div></div><div class="resize-sensor-shrink" style="position: absolute; left: 0; top: 0; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden;"><div style="position: absolute; left: 0; top: 0; transition: 0s; width: 200%; height: 200%"></div></div></div></div></div>
							<div class="col-md-7 col-lg-8 col-xl-9 dct-appoinment">
								<div class="card">
									<div class="card-body pt-0">
										<div class="user-tabs">
											<ul class="nav nav-tabs nav-tabs-bottom nav-justified flex-wrap" role="tablist">
												<li class="nav-item" role="presentation">
													<a class="nav-link active" href="#pat_appointments" data-bs-toggle="tab" aria-selected="true" role="tab">История записей на прием</a>
												</li>
												<li class="nav-item" role="presentation">
													<a class="nav-link" href="#pres" data-bs-toggle="tab" aria-selected="false" role="tab" tabindex="-1"><span>История диагнозов</span></a>
												</li>


											</ul>
										</div>
										<div class="tab-content">

											<div id="pat_appointments" class="tab-pane fade active show" role="tabpanel">
												<div class="card card-table mb-0">
													<div class="card-body">
														<div class="table-responsive">
															<table class="table table-hover table-center mb-0">
																<thead>
																	<tr>
																		<th>Дата</th>
																		<th>Доктор</th>
																		<th>Статус</th>
																		<th>Подтвердить</th>
																		<th>В ожидании</th>
                                                                        <th>чат</th>
																	</tr>
																</thead>	
																<tbody>
																	<tr>
																		<td>{{ appointment.date }}</td>
																		<td>{{ appointment.doctor.user.get_full_name }}</td>
																		<td>{{ appointment.get_status_display }}</td>
																		<td>
                                                                        <form action="{% url 'diagnosis:change_appointment_status' appointment.id 'confirmed' %}" method="post">
                                                                            {% csrf_token %}
                                                                            <button class="btn btn-sm bg-success-light" type="submit">Подтвердить</button>
                                                                        </form>
                                                                        </td>
                                                                        <td>
                                                                        <form action="{% url 'diagnosis:change_appointment_status' appointment.id 'pending' %}" method="post">
                                                                            {% csrf_token %}
                                                                            <button class="btn btn-sm bg-success-light" type="submit">В ожидании</button>
                                                                        </form>
                                                                        </td>
                                                                        <td>
                                                                            <a href="{% url 'diagnosis:chat_view' appointment.patient.user.id %}"> чат</a>
                                                                        </td>
																	</tr>
																</tbody>
															</table>
														</div>
													</div>
												</div>
											</div>

											<div class="tab-pane fade" id="pres" role="tabpanel">
                                                {% if diagnosis_history %}
												<div class="card card-table mb-0">
													<div class="card-body">
														<div class="table-responsive">
															<table class="table table-hover table-center mb-0">
																<thead>
																	<tr>
																		<th>Дата </th>
																		<th>Диагноз</th>
																		<th>Заметки пациента </th>
																	</tr>
																</thead>
																<tbody>
																	<tr>
																		<td>{{ diagnosis_history.date }}</td>
																		<td>{{ diagnosis_history.text }}</td>
																		<td>
																			{{ diagnosis_history.patient_text }}
																		</td>
																	</tr>
                                                                </tbody>
															</table>
														</div>
													</div>
												</div>
                                                {% else %}
                                                <li>История диагнозов отсутствует</li>
                                                {% endif %}
											</div>


											<div class="tab-pane fade" id="medical" role="tabpanel">
												<div>
													<a href="#" class="add-new-btn" data-bs-toggle="modal" data-bs-target="#add_medical_records">Add Medical Records</a>
												</div>
												<div class="card card-table mb-0">
													<div class="card-body">
														<div class="table-responsive">

														</div>
													</div>
												</div>
											</div>


											<div class="tab-pane active show" id="billing" role="tabpanel">
												<div>

												</div>
												<div class="card card-table mb-0">
													<div class="card-body">
														<div class="table-responsive">

														</div>
													</div>
												</div>
											</div>

										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
{% endblock %}