diagnosis/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'diagnosis'

urlpatterns = [
    path('patient/form/<int:doctor_pk>', PreliminaryDiagnosisFormView.as_view(), name='patient_form'),
    path('patient/diagnosis', PatientDiagnosisView.as_view(), name='patient_diagnosis'),
    path('doctor/list', DoctorListView.as_view(), name='doctor_list'),
    path('doctor/detail/<doctor_pk>', DoctorDetailView.as_view(), name='doctor_detail'),
    path('diagnosis/history/', DiagnosisHistoryView.as_view(), name='diagnosis_history'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('doctor/profile/create/', DoctorProfileCreateView.as_view(), name='doctor_profile_create'),
    path('patient/profile/create/', PatientProfileCreateView.as_view(), name='patient_profile_create'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('doctor-Varifing/', DoctorVarifingView.as_view(), name='octor_varifing'),

    path('role-redirect/', role_redirect, name='role_redirect'),

    path('doctor-dashboard/', DoctorDashboardView.as_view(), name='doctor_dashboard'),
    path('patient-detail/<int:pk>/', AppointmentDetailView.as_view(), name='patient_detail'),
    path('appointment/<int:appointment_id>/change-status/<str:new_status>/', change_appointment_status, name='change_appointment_status'),

    path('chat/<int:receiver_id>/', chat_view, name='chat_view'),
    path('fetch-messages/<int:receiver_id>/', fetch_messages, name='fetch_messages'),

    path('donor/registration/view', donor_registration_view, name='donor_registration'),
    path('donor/registration/confirm', donor_registration_confirm, name='donor_registration_confirm'),
    path('respond-to-request/<int:request_id>/', respond_to_doctor_request, name='respond_to_request'),
    path('doctor/requests/list/', doctor_requests_list, name='doctor_requests_list'),
    
    path('doctor-request/list/', doctor_requests_list_doctor_part, name='doctor_requests_list_doctor_part'),
    path('doctor-request/create/', create_doctor_request, name='create_doctor_request'),
    path('doctor-request/edit/<int:request_id>/', edit_doctor_request, name='edit_doctor_request'),
    path('doctor-request/delete/<int:request_id>/', delete_doctor_request, name='delete_doctor_request'),
     path('discussions/', discussion_list, name='discussion_list'),
    path('discussions/<int:pk>/', discussion_detail, name='discussion_detail'),
    path('discussions/create/', create_discussion, name='create_discussion')
]

mediog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView, LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('diagnosis/', include('diagnosis.urls', namespace='diagnosis'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<html lang="en" style="transform: none;"><head>
	<meta charset="utf-8">
	<title>Mediog</title>
	<link href="img/favicon.png" rel="icon">

	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

	<link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">

	<link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css' %}">

	<link rel="stylesheet" href="{% static 'plugins/fancybox/jquery.fancybox.min.css' %}">

	<link rel="stylesheet" href="{% static 'css/custom.css' %}">
	<style id="theia-sticky-sidebar-stylesheet-TSS">.theiaStickySidebar:after {content: ""; display: table; clear: both;}</style></head>
	<body style="transform: none;">

		<div class="main-wrapper" style="transform: none;">

			<header class="header header-custom header-fixed header-one header-space pharmacy-header fixed-top">
				<div class="container">
					<nav class="navbar navbar-expand-lg header-nav">
						<div class="navbar-header">
							<a id="mobile_btn" href="javascript:void(0);">
								<span class="bar-icon">
									<span></span>
									<span></span>
									<span></span>
								</span>
							</a>
							<a href="index.html" class="navbar-brand logo">
								<img src="{% static 'img/mediog.png' %}" class="img-fluid" alt="Logo">
							</a>
						</div>
						<div class="main-menu-wrapper">
							<div class="menu-header">
								<a href="index.html" class="menu-logo">
									<img src="{% static 'img/mediog.png' %}" class="img-fluid" alt="Logo">
								</a>
								<a id="menu_close" class="menu-close" href="javascript:void(0);">
									<i class="fas fa-times"></i>
								</a>
							</div>
							<ul class="main-nav">
								{% if user.is_authenticated %}
									{% if user.is_doctor %}
										<!-- Меню для докторов -->
										<li class="has-submenu {% if request.path == '/diagnosis/doctor-dashboard' %} active {% endif %}">
											<a href="{% url 'diagnosis:doctor_dashboard' %}">Dashboard</a>
										</li>
										<!-- Дополнительные пункты для докторов -->
									{% else %}
										<!-- Проверяем, есть ли у пользователя профиль донора -->
										{% if not user.patient.donorprofile %}
											<li class="has-submenu {% if request.path == '/diagnosis/donor/registration/view' %} active {% endif %}">
												<a style="color:red" href="{% url 'diagnosis:donor_registration' %}">Стать донором*</a>
											</li>
										{% elif not user.patient.donorprofile.approved %}
											<li class="has-submenu {% if request.path == '/diagnosis/donor/registration/confirm' %} active {% endif %}">
												<a href="{% url 'diagnosis:donor_registration_confirm' %}">Подтверждение донорства</a>
											</li>
										{% else %}
											<li class="has-submenu {% if request.path == '/diagnosis/doctor/requests/list/' %} active {% endif %}">
												<a href="{% url 'diagnosis:doctor_requests_list' %}">Список запросов</a>
											</li>
										{% endif %}
										<li class="has-submenu {% if request.path == '/diagnosis/doctor/list' %} active {% endif %}">
											<a href="{% url 'diagnosis:doctor_list' %}">Поиск доктора</a>
										</li>
										<li class="has-submenu {% if request.path == '/diagnosis/diagnosis_history' %} active {% endif %}">
											<a href="{% url 'diagnosis:diagnosis_history' %}">Мои записи</a>
										</li>
										
									{% endif %}
									<!-- Общий блок для всех аутентифицированных пользователей -->
									<li class="nav-item dropdown has-arrow logged-item">
										<a href="#" class="dropdown-toggle nav-link" data-bs-toggle="dropdown" aria-expanded="false">
											<span class="user-img">
												<img class="rounded-circle" src="{% static 'img/patient_logo.png' %}" width="31" alt="User Profile">
											</span>
										</a>
										<div class="dropdown-menu dropdown-menu-end" style="padding:5px;">
											<div class="user-header">
												<div class="avatar avatar-sm">
													<img src="{% static 'img/patient_logo.png' %}" alt="User Image" class="avatar-img rounded-circle">
												</div>
												<div class="user-text">
													<h6>{{ user.get_full_name }}</h6>
													<p class="text-muted mb-0">{% if user.is_doctor %} Doctor {% else %} Patient {% endif %}</p>
												</div>
											</div>
											<form action="{% url 'logout' %}" method="post">
												{% csrf_token %}
												<input class="dropdown-item" type="submit" value="Выйти">
											</form>
										</div>
									</li>
								{% else %}
									<!-- Пункты меню для неаутентифицированных пользователей -->
									<li class="login-link"><a href="{% url 'login' %}">Войти</a></li>
									<li class="register-btn">
										<a href="{% url 'diagnosis:register' %}" class="btn reg-btn"><i class="fas fa-user"></i>Регистрация</a>
									</li>
									<li class="register-btn">
										<a href="{% url 'login' %}" class="btn btn-primary log-btn"><i class="fas fa-lock"></i>Логин</a>
									</li>
								{% endif %}
							</ul>							
						</div>
					</nav>
				</div>
			</header>
			{% block content %}

           	{% endblock %}
		</div>


			<script src="{% static 'js/jquery-3.7.1.min.js' %}" type="text/javascript"></script>

			<script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>

			<script src="{% static 'plugins/theia-sticky-sidebar/ResizeSensor.js' %}" type="text/javascript"></script>
			<script src="{% static 'plugins/theia-sticky-sidebar/theia-sticky-sidebar.js' %}" type="text/javascript"></script>

			<script src="{% static 'plugins/select2/js/select2.min.js' %}" type="text/javascript"></script>

			<script src="{% static 'js/moment.min.js' %}" type="text/javascript"></script>
			<script src="{% static 'js/bootstrap-datetimepicker.min.js' %}" type="text/javascript"></script>

			<script src="{% static 'plugins/fancybox/jquery.fancybox.min.js' %}" type="text/javascript"></script>

			<script src="{% static 'js/script.js' %}" type="text/javascript"></script>

			<div class="sidebar-overlay"></div></body></html>

templates/base_doctor.html
{% load static %}
<html lang="en" style="transform: none;"><head>
	<meta charset="utf-8">
	<title>Mediog</title>
	<link href="img/favicon.png" rel="icon">

	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

	<link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">

	<link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css' %}">

	<link rel="stylesheet" href="{% static 'plugins/fancybox/jquery.fancybox.min.css' %}">

	<link rel="stylesheet" href="{% static 'css/custom.css' %}">
	<style id="theia-sticky-sidebar-stylesheet-TSS">.theiaStickySidebar:after {content: ""; display: table; clear: both;}</style></head>
	<body style="transform: none;">

		<div class="main-wrapper" style="transform: none;">

			<header class="header header-custom header-fixed header-one header-space pharmacy-header">
				<div class="container">
					<nav class="navbar navbar-expand-lg header-nav">
						<div class="navbar-header">
							<a id="mobile_btn" href="javascript:void(0);">
								<span class="bar-icon">
									<span></span>
									<span></span>
									<span></span>
								</span>
							</a>
							<a href="index.html" class="navbar-brand logo">
								<img src="{% static 'img/mediog.png' %}" class="img-fluid" alt="Logo">
							</a>
						</div>
						<div class="main-menu-wrapper">
							<div class="menu-header">
								<a href="index.html" class="menu-logo">
									<img src="{% static 'img/mediog.png' %}" class="img-fluid" alt="Logo">
								</a>
								<a id="menu_close" class="menu-close" href="javascript:void(0);">
									<i class="fas fa-times"></i>
								</a>
							</div>
							<ul class="main-nav">
								{% if user.is_authenticated %}
							    <li class="has-submenu {% if request.path == '/diagnosis/doctor/requests/list/' %} active {% endif %}">
									<a href="{% url 'diagnosis:doctor_requests_list_doctor_part' %}">Запросы на донорство</a>
								</li>
								<li class="has-submenu {% if request.path == '/diagnosis/doctor/list' %} active {% endif %}">
									<a href="{% url 'diagnosis:doctor_dashboard' %}">Пациенты</a>
								</li>
								{% endif %}

								{% if user.is_authenticated %}
								<li class="nav-item dropdown has-arrow logged-item" >
								<a href="#" class="dropdown-toggle nav-link" data-bs-toggle="dropdown" aria-expanded="false">
								<span class="user-img">
									<img class="rounded-circle" src="{% static 'img/patient_logo.png' %}" width="31" alt="Darren Elder">
								</span>
								</a>
								<div class="dropdown-menu dropdown-menu-end" style="padding:5px;">
								<div class="user-header">
									<div class="avatar avatar-sm">
										<img src="{% static 'img/patient_logo.png' %}" alt="User Image" class="avatar-img rounded-circle">
									</div>
									<div class="user-text">
										<h6>{{user.get_full_name}}</h6>
										<p class="text-muted mb-0">{% if user.is_patient %} Пациент {% else %} Доктор {% endif %}</p>
									</div>
								</div>
									<form action="{% url 'logout' %}" method="post">
    									{% csrf_token %}
    									<input class="dropdown-item" type="submit" value="Logout">
									</form>
								</div>
							</li>
								{% else %}
								<li class="login-link"><a href="{% url 'login' %}">Login</a></li>
								<li class="register-btn">
									<a href="{% url 'diagnosis:register' %}" class="btn reg-btn"><i class="fas fa-user"></i>Регистрация</a>
								</li>
								<li class="register-btn">
									<a href="{% url 'login' %}" class="btn btn-primary log-btn"><i class="fas fa-lock"></i>Войти</a>
								</li>
								{% endif %}

							</ul>
						</div>
					</nav>
				</div>
			</header>
			{% block content %}

			{% endblock %}
		</div>


			<script src="{% static 'js/jquery-3.7.1.min.js' %}" type="text/javascript"></script>

			<script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>

			<script src="{% static 'plugins/theia-sticky-sidebar/ResizeSensor.js' %}" type="text/javascript"></script>
			<script src="{% static 'plugins/theia-sticky-sidebar/theia-sticky-sidebar.js' %}" type="text/javascript"></script>

			<script src="{% static 'plugins/select2/js/select2.min.js' %}" type="text/javascript"></script>

			<script src="{% static 'js/moment.min.js' %}" type="text/javascript"></script>
			<script src="{% static 'js/bootstrap-datetimepicker.min.js' %}" type="text/javascript"></script>

			<script src="{% static 'plugins/fancybox/jquery.fancybox.min.js' %}" type="text/javascript"></script>

			<script src="{% static 'js/script.js' %}" type="text/javascript"></script>

			<div class="sidebar-overlay"></div></body></html>